### ISSUE TITLE
v2.1.1 Error withdrawing from Vault

### ISSUE THREAD

**Issue by jesusangel72** [bittorrent/btfs-dashboard#13]
BTFS 2.1.1 . No matter the amount, with decimal or without, if I want to withdraw 2117 BTT I get error "Amount:2.117.000.000.000.000.000.000 Cannot Be Parsed" seems like add 18 zeros so too big to be parsed, appart of  not enought balance
![2022-03-11 18_07_15-BTFS Dashboard](https://user-images.githubusercontent.com/37635882/157914285-b74391ed-3658-4af1-bffc-b9cb0ec62b45.png)
e

**Comment by lyceus80** [comment]
How to fix that ?

**Comment by jesusangel72** [comment]
I hope developpers fix it in the next release, I don't know if it is a btfs-dashboard error or a go-btfs one, it happens in bttc-address withdrawal, at least for that I got private key and use it in metamask

**Comment by NikeGOGO** [comment]
This problem has been identified, should be fixed in the next release. Keep watching.

**Comment by zhimipe** [comment]
> How to fix that ?

1. Without closing the node, open a new cmd window
2. btfs storage balance (will show the balance)
3. Withdraw funds from btfs storage (insert balance)
