### ISSUE TITLE
10 GB of memory on Windows

### ISSUE THREAD

**Issue by paveldvorak5** [bittorrent/btfs-dashboard#16]
version 2.1.1

![image](https://user-images.githubusercontent.com/14863835/160596788-69c852e8-7f81-44f1-a546-cf62e661e542.png)
[LOG.zip](https://github.com/bittorrent/btfs-dashboard/files/8370670/LOG.zip)
Can't see anything useful in the logs

**Comment by Big-Daddio** [comment]
Same problem here as well with 2.1.1, updated a week or so ago from 1.6, starts out at a few hundred megabytes then over a few days i'm up to 5 GB.
