### ISSUE TITLE
Vault withdraw problem...

### ISSUE THREAD

**Issue by ZeroCool1974-BR** [bittorrent/btfs-dashboard#20]
I have cashed some cheques today and made some withdraws from vault too, but suddenly I can't withdraw from vault anymore, always the same error as shown on attached image.

https://scan.btfs.io/#/node/16Uiu2HAmQUxZexD9ShqirzMEM2CjRx9LpyqPzqfXmAvkmCbW4duL

![vault_withdraw](https://user-images.githubusercontent.com/91059173/162587489-15876d58-10b4-46c6-b53c-9bd3f9b9cf02.jpg)

**Comment by ZeroCool1974-BR** [comment]
I manage to withdraw using cmd:

![withdraw](https://user-images.githubusercontent.com/91059173/162588841-3ea89ad4-62b7-442d-93d0-c831d94f2207.jpg)

**Comment by juchambo** [comment]
Same problem here, but can´t withdraw using CMD neither.
