### ISSUE TITLE
btfs Contracts

### ISSUE THREAD

**Issue by daniguebar** [bittorrent/btfs-dashboard#26]
Hey I am reciving contractas and checks but it didn't shows on UI, I see on comand line on windows.

![imagen](https://user-images.githubusercontent.com/95375166/177982881-13582abf-17ec-4c48-b292-f43b2c723f37.png)
![imagen](https://user-images.githubusercontent.com/95375166/177982922-ffb2a5bf-16c1-4905-a78e-e0f60cfcc7e5.png)

**Comment by rgouzal** [comment]
@daniguebar what is the command line you used to view contracts received?

**Comment by daniguebar** [comment]
not used any command line, running node through command line and this is what I see
