### ISSUE TITLE
All  "SCORE FACTORS" show NaN and 0%

### ISSUE THREAD

**Issue by VitaliyAT** [bittorrent/btfs-dashboard#3]
Look like something work wrong - all score factors show NaN and 0%. Node have 0 score too. Status is "Connebted"

**Comment by VitaliyAT** [comment]
wait - not help - more then 24 hours waiting give nothing

**Comment by petrrr89** [comment]
UPTIME  -- % ,  Online - 1033 , Connected HOST SCORE 0 , Online Duration (NaN %)  in 15 days

**Comment by VitaliyAT** [comment]
2.1.0 work the same
