### ISSUE TITLE
Online Proof discourages new users

### ISSUE THREAD

**Issue by MilNoslen** [bittorrent/btfs-dashboard#30]
The Online Proof bleeds your account unnecessarily if you get no contracts, which further discourages new users from joining. With the update to 2.2.0, my contracts have dropped from constant mid 20s to 0. I usually leave a few hundred BTT for gas. With 0 contracts and constant heartbeat checks, I'll actually be close to 0 BTT left in my wallet.

**Comment by oldcityws** [comment]
I agree with this point.

**Comment by oldcityws** [comment]
I think online proof could be done as a seeded file for each account.  IF the seeded file is accessible, then the node is online.  Boom, no BTT expenditures.

**Comment by Degs42** [comment]
At the time of writing average trx fee per heartbeat is 35 BTT, that's $0.000027. So for one year that's 12,775 BTT or $0.0099!

I think everyone who is really interested in this project can (at least) sacrifice 1 penny a year... 😅

**Comment by MilNoslen** [comment]
> At the time of writing average trx fee per heartbeat is 35 BTT, that's $0.000027. So for one year that's 12,775 BTT or $0.0099!
> 
> I think everyone who is really interested in this project can (at least) sacrifice 1 penny a year... 😅

I mean yes I get it promotes decentralization and authentication, but imagine the user who's new.

Either they get TRX and then have to figure it out how to swap it to BTT, or they buy BTT directly.
Then imagine they're told they have to bridge it, which costs TRX. If they didn't know what gas is, So now they have to buy TRX again.

So now they bridge it, and somehow they figure out how to setup BTFS. They have a low score, takes a while to hit 10 or "Happy Face" now in the new UI. Now their money essentially gets drained with heartbeat.

So no, it's not just a "sacrifice 1 penny a year"
