### ISSUE TITLE
Dashboard not working after update 2.2.0 to 2.2.1

### ISSUE THREAD

**Issue by Cr-opas** [bittorrent/btfs-dashboard#34]
![image](https://user-images.githubusercontent.com/112861208/188418712-4dcbd309-b5ed-4e89-8821-8317dc05519f.png)

**Comment by jesusangel72** [comment]
Go to settings and click Submit button on the top right

**Comment by Cr-opas** [comment]
i got error "Setting Failed, Please Check If You Are Using A Valid API URL!"

**Comment by Cr-opas** [comment]
This is strange but dashboard working if i use this link https://dashboard.btfs.io/#/admin/dashboard

**Comment by Cr-opas** [comment]
Perhaps it works this way because I have the entry data in the config file?
`API:{
HTTPHeaders:{
Access-Control-Allow-Methods:[
"PUT"
"GET"
"POST"
]
Access-Control-Allow-Origin:[
"https://dashboard.btfs.io"
]
}
}`

**Comment by oldcityws** [comment]
Did you go to Settings and click Submit?  Seems pointless but someone told me to do that and mine is now working perfectly.

**Comment by Cr-opas** [comment]
yes it was me, because in this thread I was advised to do the same.  But it didn't help me.
