### ISSUE TITLE
Connection failure - unknown cause

### ISSUE THREAD

**Issue by oldcityws** [bittorrent/btfs-dashboard#35]
![image](https://user-images.githubusercontent.com/42473932/190530573-3ed2943b-478d-40c6-95e5-eb3271d9d308.png)

I just went through problems with it not connecting because something was hogging port 8080.

Cured that with stopping a few apps and rebooting a few times.  Still don't know what I did to actually solve the port issue, but here I am again. playing monkey at the keyboard.  Anyone know how to fix this?

**Comment by Cr-opas** [comment]
try this link `https://dashboard.btfs.io/#/admin/settings`

**Comment by oldcityws** [comment]
![image](https://user-images.githubusercontent.com/42473932/190646314-9d5a4e80-3921-47b0-90ae-f2d1487e5f01.png)
is what pops up.

**Comment by oldcityws** [comment]
![image](https://user-images.githubusercontent.com/42473932/190646817-24ccd3ff-800c-4f12-bb62-6605c02a396d.png)
is what shows up when I click Dashboard.

**Comment by Cr-opas** [comment]
What version of btfs is running? Try run latest version 2.2.1

**Comment by oldcityws** [comment]
I am using the latest release that was published as of 15 days ago, the
ready-to-use compiled version for Windows.

- 2.1.3

**Comment by Cr-opas** [comment]
latest version published as of 15 day ago: `https://github.com/bittorrent/go-btfs/releases/tag/btfs-v2.2.1`

**Comment by oldcityws** [comment]
![image](https://user-images.githubusercontent.com/42473932/190656991-72970cca-b001-4e8e-8c18-02f2a701621a.png)

**Comment by Cr-opas** [comment]
ok, go to settings and click Submit button on the top right

**Comment by oldcityws** [comment]
![image](https://user-images.githubusercontent.com/42473932/190657787-1a1027b1-27a8-40d7-9229-c359aff5485c.png)

**Comment by Cr-opas** [comment]
working now?

**Comment by oldcityws** [comment]
WOW.  YES.  THANK YOU.  Now, how do we start earning BTT on this system?
![image](https://user-images.githubusercontent.com/42473932/190659096-89be91cc-775c-4b4e-86bf-3f2f4e0e059b.png)
