### ISSUE TITLE
Unable to rent storage on BTFS- please help

### ISSUE THREAD

**Issue by Bullish2Extreme** [bittorrent/btfs-dashboard#37]
Hello community,
I am new to BTFS and struggling to rent my storage- please see below and assist me what should I do next, thank you in advance.
<img width="836" alt="image" src="https://user-images.githubusercontent.com/114254395/192030005-190ccc68-fcd9-409a-9cb8-bc20caf5d496.png">

**Comment by Degs42** [comment]
1. Update your dashboard
2. Deposit BTT on the BTTC address
3. Exchange BTT to WBTT
4. Deposit WBTT on the Vault address
5. Open the Files tab and import the files or directory you want to upload _notice: this step only uploads to your local node_
6. Copy your file/directory hash (starting with 'Qm')
7. Open Console/Terminal in the directory of your btfs binary
8. Execute command: `btfs storage upload <file-hash> --copy=0 --len=30` with `--copy` you set the number of copies to be saved (more copies higher safety) with `--len` you set the number of days you want this to be stored (has to be at least 30 days)
9. Your files are now uploading. You can check the status with the command: `btfs storage upload <session-id> status` you can find your `<session-id>` in the last output.
10. If you have enough WBTT in your Vault and your node finds enough hosts, your files will be uploaded. This process might take a while. You can always check the status with the previous step.
11. To download your files use: `btfs get <file-hash>`. To remove your files use: `btfs rm <file-hash>`.
12. You can also try to access your data via this gateway: https://gateway.btfs.io/btfs/<file-hash>

**Comment by oldcityws** [comment]
I would think there would be a way to "rent" the storage from the Dashboard instead of having to go through Terminal to do that.
