### ISSUE TITLE
BTFS with no gain

### ISSUE THREAD

**Issue by Michael8878** [bittorrent/btfs-dashboard#41]
I've been leaving the computer on for 3 days and I'm not seeing any gains. I'm just noticing spending on something related to online contract gas. What would that be? and how do i increase my earnings?

![BTFS1](https://user-images.githubusercontent.com/82910750/205040142-c9af7241-a618-4802-b881-704543ed8baf.png)
![BTFS2](https://user-images.githubusercontent.com/82910750/205040737-d5e37884-8475-4ab7-8432-965cb225375f.png)

**Comment by Sophia-yu-kk** [comment]
Hi, BTFS node status is "good" or the old version of the node score is 8 or more to have a chance to get a contract. However, the probability of an individual node getting a contract is not certain, and there is competition for contracts between nodes across the network.

Nodes submitting online proof contracts are required to consume gas fees, https://docs.btfs.io/docs/btfs20-architecture, which can be found in the BTFS node architecture diagram.
