### ISSUE TITLE
Wrong or not full instraction of usage

### ISSUE THREAD

**Issue by VitaliyAT** [bittorrent/btfs-dashboard#5]
You write in Usage section om read.me :
btfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["*"]'
It give me:
Error: failed to unmarshal json. invalid character '\'' looking for beginning of value

**Comment by VitaliyAT** [comment]
Also you wrute: "Follow below commands and then restart the BTFS node." What that normally mean? I should start btfs in 1st window, run this commands in other window and restart (switch-off that already work and run it again) ?

**Comment by simbadMarino** [comment]
I agree , improvements on documentation are needed :)

**Comment by Cr-opas** [comment]
For Windows OS, you need to replace the outer quotes and escape the inner ones. Like this btfs config --json API.HTTPHeaders.Access-Control-Allow-Origin "[\"*\"]"
