### ISSUE TITLE
Invalid speed units

### ISSUE THREAD

**Issue by ruXlab** [bittorrent/btfs-dashboard#50]
Hello

The speed units reported in the dashbord is not correct

![image](https://user-images.githubusercontent.com/1110234/219428515-0eaf5e42-c618-42f9-985a-ba4d31cfe831.png)

It's pretty easy to check yourselves by using gotop/bmon

**Comment by CrCati** [comment]
Thank you for your feedback, you're right, and the issue has already been fixed now.
