### ISSUE TITLE
Leak memory issue on Windows 7

### ISSUE THREAD

**Issue by turbowebmaster** [bittorrent/btfs-dashboard#56]
Hi staff,

we have a big issue of memory consumption with new btfs version 2.3.2. On Windows 7 btfs has consumed for itself in a couple of minutes about 3 gigabyites of memory! And it was impossible for btfs dashboard to connect with btfs daemon... I had to stop new btfs version and downgrade immediately to 2.3.1 that works fine. I suspect that also other user are experiencing the same time of issue, please take a look to this Twitter user (that Twitter account is not of my own...): https://twitter.com/konantxp/status/1673258787719856133 . Thank you for your attention, bye.

**Comment by CrCati** [comment]
Hi, @turbowebmaster; thanks for your feedback. Since the number of connections increases, the mem consumption will also increase. On Win7, the node may cost about 3 gigabytes of memory. You can keep it running and monitor the memory consumption with the 2.3.2 version. 
'And it was impossible for btfs dashboard to connect with btfs daemon,' about this issue, could you please check the 'Settings' page? Is the 'API Endpoint, RPC ADDRESS, Storage Path' value correct?

**Comment by CrCati** [comment]
Hi, @lsv29081973; just to make sure, does the mem consumption keeps increasing as time goes on if you use v2.3.2? The more connections a node has, the more chances to get contracts. I upgraded my node(OS is Ubuntu 20.04) from v2.3.1 to v2.3.2 yesterday, 4093 connected and the mem consumption is about 2.5G.
<img width="382" alt="image" src="https://github.com/bittorrent/btfs-dashboard/assets/122080967/871132e3-6178-4b17-905e-63f1934a2f51">
<img width="882" alt="image" src="https://github.com/bittorrent/btfs-dashboard/assets/122080967/f24c2ade-e2c1-4ba4-b7f6-5fb455e6a561">

**Comment by CrCati** [comment]
The CPU usage is constantly 55%+ or just some spikes occasionally?

**Comment by brianbc2021** [comment]
I have 2 VPS, both running Linux. One of them, located in the US, received 3 contracts last month, while the other, located in Germany, did not receive any contracts. Although contract receiving is random, based on my experience with these 2 nodes, I believe that the location of the nodes can affect the receiving result.

**Comment by lsv29081973** [comment]
> The CPU usage is constantly 55%+ or just some spikes occasionally?

60 sec video
[Task Manager 2023-06-27 15-46-44.zip](https://github.com/bittorrent/btfs-dashboard/files/11881084/Task.Manager.2023-06-27.15-46-44.zip)

**Comment by lsv29081973** [comment]
pay attention to the traffic, this has not happened before, the size of the occupied space does not change, and the traffic has increased by an order of magnitude.

**Comment by turbowebmaster** [comment]
Hi @CrCati, thank you very much for your assistance. Ok now I know that the RAM consumption for new version of BTFS is much higher. I have to say that also CPU usage is very much higher now (about 30-60% of usage for a CPU  i7 with 4 cores, 8 threads and 3 GHz of frequency). I can confirm you that the memory usage is much more than 3GB, now BTFS is consuming 4.3GB and it had a peak consumption of quite 5GB... Bandwith consumption is in the range 1,5-3 Mbit for download stream and in the range 3-7 Mbit for upload stream. I can now say you that the issue with BTFS dashboard solved by itself and it works fine. When the dashboard didn't work I noticed some errors in the web developer console regarding the javascript file "vendor.b0bd802c.chunk.js": this file was unreachable, now it's ok but I don't know why, I only can say that I didn't change anything in the "Settings" page. If it can help you in your development I noticed that some web files of the dashboard have a CORS issue, as you can say in the screenshot. Moreover, the files mentioned in the screenshot give 404 error if you try to reach them using a browser.

![firefox_kByL04Ggro](https://github.com/bittorrent/btfs-dashboard/assets/40826111/cddee5af-728a-489b-a63c-a50152c0b3d4)

Finally I hope that this very big increment of system resources usage by BTFS will correspond to a big increase of contracts quantity (for now I obtained very very few contracts for me that I am from Italy and that I am been sustainig my BTFS node for about two years...) and/or a remuneration with periodic aidrops because otherwise there are no rasonable incentives for maintaining a BTFS node (and you know it very well...).

The last thing: in your opinion is possible to run a BTFS node on a Raspberry 4 pi model b? It has linux system, quad code CPU with 1,5 GHz of frequency and 8GB of RAM, moreover you can connect to it 2 disks using a fast USB 3: I could connect to it my disk where already now I have my BTFS node files. Thank you very much for your reply!

**Comment by CrCati** [comment]
Hi, @turbowebmaster. Thanks for your feedback. About the CORS issue, I'll forward your feedback to the community developers. As to Raspberry with the Linux system, I don't have one, but someone in the community said that they were running a BTFS node on Raspberry. So, I think it's OK.

**Comment by CrCati** [comment]
Hi, @turbowebmaster; about the CORS issue, it should be OK now; you can have a try.

**Comment by turbowebmaster** [comment]
Ok @CrCati, CORS issue is solved! Thank you for all, bye!

**Comment by CrCati** [comment]
Since resource consumption is not increasing in my testing nodes, I am going to close this issue for now. However, if the issue persists or there are new developments, feel free to reopen it.

**Comment by lsv29081973** [comment]
The problem hasn't gone away, it's only getting worse. CPU usage is on the rise. The Internet channel is clogged with connections, which causes the router to freeze. I don’t have the opportunity to sit nearby and reboot the router every 2-3 hours, alas, but I disable BTFS.

**Comment by CrCati** [comment]
From the video you posted, CPU usage falls between 10% to 60%, mostly around 40%. Currently, what's the number of connections, and what's the CPU usage range? Could you please use 'resmon' in Windows to monitor bandwidth and other resource consumption?

**Comment by lsv29081973** [comment]
resource monitor, when BTFS is running, it consumes 25-32% of the processor itself))) so the BTFS consumption in it will be shown incorrectly

connections = 9500+, the longer online, the more resources it consumes, when I turned it off it reached 90% of the processor load

**Comment by turbowebmaster** [comment]
Hi @CrCati

I write here in this closed ticket because I think that my new question is contextual and that what I will say can interest people that wrote here in the past days. As I announced last time here, I transferred my BTFS host from Windows to a Raspberry Pi 4 model b with 8 GB of RAM. The host seems to work fine now and the usage of system resources is extremely low: about 1-4% of CPU and 450MB of RAM. And Raspberry consumes only 6 Watts/h of electricity (the maximum is 15 Watts/h...). But I notice an other issue: the quantity of hosts connected is very low. While before with Windows I had about 7000-8000 hosts connected now I have only about 400-700 hosts connected to my BTFS node on Raspberry. And this situation has been going on for several days because I transferred my BTFS host about five days ago. Is this normal?

Thank you very much for your assistance...

![btfs_host_connected](https://github.com/bittorrent/btfs-dashboard/assets/40826111/03646d37-bd65-447f-afec-3a6a4cb51f37)

**Comment by CrCati** [comment]
Hi, @turbowebmaster; OK, is the node running on Raspberry Pi 4 also v2.3.2, the same with your windows7? Have you changed the 'config' file in the .btfs directory? Especially the values of `Swarm.ConnMgr` and `Swarm.ResourceMgr.Limits.System`. If possible, please share your `config` files in win7 and Raspberry nodes. By the way, what's the uptime and host score of the node running on Raspberry Pi for now?

**Comment by turbowebmaster** [comment]
Hi @CrCati, yes, the node running on my Raspberry is v2.3.2. The uptime host is now 99% and host factors scores are always 3/3 for online duration, host age, version and activity. I didn't change the config file, I pointed the new installation of BTFS on Raspberry to the disk that before I used for BTFS on Windows. I didn't change the config file and I put a copy of it in attachment.

Thank you!
[btfs_config_copy.txt](https://github.com/bittorrent/btfs-dashboard/files/12090505/btfs_config_copy.txt)

**Comment by CrCati** [comment]
Hi, @turbowebmaster; the Raspberry may have different network conditions with the win7 PC. In the `btfs_config_copy.txt`, your access IP is 127.0.0.1. Other nodes connect to your Raspberry Pi node via NAT. You can check the number of peers with this command `btfs swarm peers --direction=true | awk '{print $2}' | sort | uniq -c`. The output of this command execution in the win7 PC node should be greater than the result in the Raspberry Pi node. If you have a public IP address, you can put it in the config items on the Raspberry Pi node. The connections should increase after that.

**Comment by CrCati** [comment]
Hi, @turbowebmaster; what is the memory size of your Windows 7 PC?

**Comment by CrCati** [comment]
Got it; yes, that's normal.
