### ISSUE TITLE
DHT ERROR

### ISSUE THREAD

**Issue by Cr-opas** [bittorrent/btfs-dashboard#58]
Win serv 2008R2 (one node)
Ubuntu 22.04 (second node)
ver BTFS 2.3.1 and 2.3.2 two nodes have some error
This error has been haunting me for several months, and I noticed that my node has ceased to be confirmed because of this, I have a low rating, while the node is running 24/7, it turns out that I’m just wasting electricity for three months now, I don’t have a single contract how to get rid of it from this problem?

Windows error 
![1](https://github.com/bittorrent/btfs-dashboard/assets/112861208/85946a01-cbcb-4c2f-bb40-68d91a71bb39)
Ubuntu error
![1](https://github.com/bittorrent/btfs-dashboard/assets/112861208/791f0978-90a5-4b2f-9ace-f3bda06b5f4d)

**Comment by CrCati** [comment]
Hi, @Cr-opas; thank you for your feedback, and we apologize for the confusion. The issue you mentioned, 'ignoring incoming dht messages while not in server mode,' is a known issue. We have recorded it, and our community developer will be actively working on resolving it. I'll close this issue first. Please feel free to reopen it if you have more information to share.
