### ISSUE TITLE
Files not delete.

### ISSUE THREAD

**Issue by VitaliyAT** [bittorrent/btfs-dashboard#6]
I am select files to delete. No them in list but they are on my disk. They are not mpve out or deleted from disk.

**Comment by VitaliyAT** [comment]
STORAGE - show their size on disk and I see pakages from File Explorer

**Comment by simbadMarino** [comment]
Those files are not supposed to be deleted from your disk but from the repo itself, are u using the `btfs rm QmHash` Command? If yes you are only removing them from the .btfs  folder repository
