### ISSUE TITLE
Feature Request: Retain Statistics on Network Activity

### ISSUE THREAD

**Issue by oldcityws** [bittorrent/btfs-dashboard#69]
If there is a way to declare a set timeframe for which the statistical information regarding network activity can be retained for a period of time, that would be a lot more helpful than the IRT graph.  

I wish we could edit a setting that gives us options such as (1) NO data retention (2) number of minutes (3) number of hours (3) number of days (4) number of months ... in bandwidth data used.

**Comment by yu-btc** [comment]
Thank you very much for your feedback, the requirement has been recorded.
