### ISSUE TITLE
Nothing works

### ISSUE THREAD

**Issue by AlterX76** [bittorrent/btfs-dashboard#7]
Nothing works on btfs 2.. Compile it on your own, throws errors, there are no requirements in terms of what needed for compilation (make, gcc, go and so on...) and what versions. I finally stumbled upon a pre-compiled windows version (after I have tried to compile it on linux, windows and rasp4), now that seems to be aligned to the documentation, the dashboard does not work and it suggests me to go to discord for help (behind invite) that of course does not work!

![image](https://user-images.githubusercontent.com/7677795/152586365-228e71ce-c8e1-42ea-a4f9-c607994be96b.png)

![image](https://user-images.githubusercontent.com/7677795/152586422-8d186ce3-7828-451d-813b-0394274ba58c.png)

**Comment by simbadMarino** [comment]
Btfs2 works even on mobile mate, if you are having an specific problem please add more details so we can help you better.

A good bug report must contain at least the following:

- Brief background or problem description
- Your system details ( OS, architecture, distro, etc)
- Test steps 
- Expected results
- Actual results 
Please provide the above so we can support in a better way

**Comment by AlterX76** [comment]
It does not really matter...I just downloaded the pre compiled binary for windows amd64, v 2.0.2
followed the docs, init and so on...
daemon is running, the dashboard does not. Just discovered that going to settings and force the save with submit button, temporarily fix the disconnection, so I can see all the content in the dashboard. If I close it then I have to force again the settings....

**Comment by VitaliyAT** [comment]
I had the same problem, but wait about 15 minits and connection was on.

**Comment by AlterX76** [comment]
ok...really working then!
Even if I change the API endpoint, it does not do anything

**Comment by VitaliyAT** [comment]
Yep! And you gone go to my issue:
https://github.com/bittorrent/btfs-dashboard/issues/3

**Comment by jorkufrbg** [comment]
I'm kinda losing patience with this project. 
Node not connecting, the dashboard shows the same thing as op's picture.
I followed the instructions in the documentation to no avail. Unlike btfs 1.0 docs, the v2.0 ones are a sheer mess at best.
Will this be resolved any time soon?
OS: Ubuntu server x64

**Comment by simbadMarino** [comment]
> Yep! And you gone go to my issue:
> #3
> Around 4 days it so. I am not alone - youtube staff have the same - no aswers, no reaction. Even "we are working on it" or even "we know about this" from official supports. Nothing. Even here - like closest place from developers.

Would you please post the configuration steps you are following? I’ve seen some commands are messing up with the configuration. I might help to reproduce the issue and then find a way out of it

**Comment by VitaliyAT** [comment]
1. Download
2. btfs init
3. btfs daemon
4. Gas getting
5. waiting

**Comment by VitaliyAT** [comment]
2.1.0 work the same
