### ISSUE TITLE
Cant see Files on go-btfs node dashboard (permanent cycling circle) + wrong version in dashboard

### ISSUE THREAD

**Issue by dipol0** [bittorrent/btfs-dashboard#82]
Hi.
Host:

Ubuntu 22.04
_Linux 6.8.0-48-generic #48-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 27 14:04:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux_

Docker
_Docker version 24.0.7, build 24.0.7-0ubuntu4.1_

Build container BTFS v3.1.0 node from https://github.com/bittorrent/go-btfs/releases/tag/btfs-v3.1.0 and start it
I connect to btfs container as data previously dir. BTFS node started and can see in webui, but:

**1. In dashboard show wrong version:**
![Выделение_685](https://github.com/user-attachments/assets/94c8a836-5f53-4a07-97a7-948cd59dd893)
if go to link from dashboard to https://scan.btfs.io or direct connect to container btfs node it show normal version:
![Выделение_684](https://github.com/user-attachments/assets/0132b590-5f25-4167-a3af-dedc4317808c)
![Выделение_683](https://github.com/user-attachments/assets/2990000c-8bd4-49a7-852e-41fce07ee54f)

**2. If go Dashboard - Files - don't show btfs/s3 and cant see previously uploaded files. Just permanently rotating blue circle:**
![Выделение_682](https://github.com/user-attachments/assets/e3805e16-4383-4cc2-a722-d0e8df72315e)

**Comment by yu-btc** [comment]
Hello, thank you for your feedback.
1. I suggest you try to clear your browser cache to see if the version number can be updated successfully.
2. 
![image](https://github.com/user-attachments/assets/6b06af78-4955-4146-84ca-1fedc841b0ad)
![image](https://github.com/user-attachments/assets/85364c22-08fd-40f4-8f1f-f14c16e9c3f0)
For this problem, you may need to check your configuration.
![image](https://github.com/user-attachments/assets/5f4e9858-96cc-4e8a-ba7a-8d7a8ed1d365)

Have a nice day.

**Comment by dipol0** [comment]
@yu-btc 

Hi.

I create new container. Run it. Get from CONFIG file. Stop container. Delete container.
Modify "Identity" block CONFIG to my from previously backuped config file.
Start new container with pass-through previous node data folder with modified CONFIG with my "Identity" block. + S3API Enabled in config.
Go to _http://btfs_node_ip/hostui_
In field change API string foe me. Make auth password... press Next//and get it:

![Выделение_686](https://github.com/user-attachments/assets/cf45c3c1-3f0e-413f-b6be-353de9e3b500)

Goto dashboard:
![Выделение_687](https://github.com/user-attachments/assets/9a44b7a7-651a-4410-9dcc-81ec2fdb78cb)

BUT if i select Cheques / Proof / Peers / Files i see righr blank field.
![Выделение_689](https://github.com/user-attachments/assets/04584817-9ccc-4f1d-93d3-c9aa18360264)

Whats wrong now? Need wait to sync (my prev node be stopped ~ half year...year) ? Or may be i crush file permissions? Or something else....

**Comment by dipol0** [comment]
UPD. Found few difference in config. Fix it and now can see in WebUI All, but on Files - BTFS Native API i see permanently rotating circle:
![Выделение_692](https://github.com/user-attachments/assets/178ff744-eb18-4c23-8f1b-a54e0020924f)
I connect to BTFS docker container directly. List BTFS / and see 2 files (previously uploaded a long time ago). First i remove one JPG file - OK. Then i try remove Opnsesne install image file, but cursor wait and can back to welcome string # 
![Выделение_693](https://github.com/user-attachments/assets/bb5bec19-6c85-4e56-848a-be94af97f8ec)

**Comment by yu-btc** [comment]
Hello, please check if the config field EnableTokenAuth is true. Cause the BTFS v3.1.0 has been updated. The interface has added a token field. You need to set a password on the dashboard before logging in. thanks for your feedback.

**Comment by dipol0** [comment]
> Hello, please check if the config field EnableTokenAuth is true. Cause the BTFS v3.1.0 has been updated. The interface has added a token field. You need to set a password on the dashboard before logging in. thanks for your feedback.

Hi. Yes. I clear browser cache. Set "EnableAuthToken = true" in config file. Create password... See S3 Files but on BTFS API tab - permanently rounded circle. ((
![Выделение_696](https://github.com/user-attachments/assets/2b626cca-d25b-4314-8c93-3b405d165cb6)
![Выделение_695](https://github.com/user-attachments/assets/55164666-2b1d-4b8e-8e60-e8fea9e88f89)
![Выделение_694](https://github.com/user-attachments/assets/b63d5a93-6ae3-4f46-985a-010367aabdec)

**Comment by yu-btc** [comment]
Could you please take a look at the error message on the server? We will help you check the cause. Thank you.

**Comment by dipol0** [comment]
@yu-btc 
Where i can see it? Now strange things... after btfs files rm /Opnsense....bz in console cursor stop. I restart container...but now i cant login BTFS Dashboard WebUI.

"Looks like your node is not connected"

![Выделение_697](https://github.com/user-attachments/assets/82a47f44-b966-4b14-bb51-705fc68d6d64)

BTFS container log from portainer:

> 
> Changing user to btfs
> btfs version 3.1.0
> Found BTFS fs-repo at /data/btfs
> Initializing daemon...
> go-btfs version: 3.1.0-c0cc0bc
> Repo version: 10
> System version: amd64/linux
> Golang version: go1.22.8
> Repo location: /data/btfs
> Peer identity: 16U...............................................................eXJb
> the address of Bttc format is:  0x1F...........................................................9d0
> the address of Tron format is:  TCrR...............................................................xQ
> Guide: http://0.0.0.0:5001/hostui
> InitToken:  199 map[TRX:0xEdf53026aeA60f8F75FcA25f8830b7e2d6200662 USDD:0x17F..........................................A6d1 USDT:0xdB2..................................................4a15 WBTT:0x231............................................7f3C]
> self vault: 0x05........................................................04 
> vault implementation is updated: 0x5...............................................................72e
> Swarm listening on /ip4/127.0.0.1/tcp/4001
> Swarm listening on /ip4/172.17.0.7/tcp/4001
> Swarm listening on /ip6/2001:db8:1::242:ac11:7/tcp/4001
> Swarm listening on /ip6/::1/tcp/4001
> Swarm listening on /p2p-circuit
> Swarm announcing /ip4/127.0.0.1/tcp/4001
> Swarm announcing /ip4/172.17.0.7/tcp/4001
> Swarm announcing /ip6/2001:db8:1::242:ac11:7/tcp/4001
> Swarm announcing /ip6/::1/tcp/4001
> API server listening on /ip4/0.0.0.0/tcp/5001
> Dashboard: http://0.0.0.0:5001/dashboard
> Gateway server listening on /ip4/0.0.0.0/tcp/8080
> Remote API server listening on /ip4/127.0.0.1/tcp/5101
> Daemon is ready
> S3-Compatible-API server started, endpoint-url: http://0.0.0.0:6001
> Experimental.Analytics is overridden by Experimental.StorageHostEnabled
> Current host stats will be synced
> Current host settings will be synced

**Comment by yu-btc** [comment]
OK, please use the F12 keyboard again, take a screenshot and upload it, and let’s take a look at the error message of the API. thanks

**Comment by dipol0** [comment]
> OK, please use the F12 keyboard again, take a screenshot and upload it, and let’s take a look at the error message of the API. thanks

![Выделение_698](https://github.com/user-attachments/assets/5c175919-6701-460b-ad9d-020e334b6c0f)

**Comment by yu-btc** [comment]
<img width="966" alt="image" src="https://github.com/user-attachments/assets/95b95691-c7f5-4bd5-a2df-206c9a8ac879">
hi，Please provide this page screenshot, many thanks.

**Comment by dipol0** [comment]
@yu-btc aaa...you about DevTools in breowser )) In my case F12 system defined another action )) I use Firefox Dev Edition now.

Sorry, may be i set not correect addres. With this all work - i can login.

> "Access-Control-Allow-Origin": [
>         "http://192.168.0.50:5001"
> 
But on Files - BTFS NAtive API - rotation blue circe permanently

![Выделение_699](https://github.com/user-attachments/assets/9ec5820e-964b-4954-b16c-1161c6d500d5)

**Comment by dipol0** [comment]
I really can understand what happened ))) Ok... If i create new node, stop it and change IDENTITY block in config ??? Yes? i know some info about earned bttc etc be lost, but its can work ?

**Comment by dipol0** [comment]
![Выделение_702](https://github.com/user-attachments/assets/479388f2-c7cc-4865-a343-06d2dab67887)

**Comment by dipol0** [comment]
And now on Cheques / Proof / Peers / Files i see right blank field. (((

![Выделение_703](https://github.com/user-attachments/assets/6e92e29e-a61f-43a6-ae88-6254c9c0bd33)

**Comment by dipol0** [comment]
`
2024-11-09T11:58:27.531804313Z Swarm announcing /ip4/172.17.0.7/tcp/4001

2024-11-09T11:58:27.531809062Z Swarm announcing /ip6/2001:db8:1::242:ac11:7/tcp/4001

2024-11-09T11:58:27.531814231Z Swarm announcing /ip6/::1/tcp/4001

2024-11-09T11:58:27.531966625Z API server listening on /ip4/0.0.0.0/tcp/5001

2024-11-09T11:58:27.531984993Z Dashboard: http://0.0.0.0:5001/dashboard

2024-11-09T11:58:27.532261776Z Gateway server listening on /ip4/0.0.0.0/tcp/8080

2024-11-09T11:58:27.532282169Z Remote API server listening on /ip4/127.0.0.1/tcp/5101

2024-11-09T11:58:27.532365421Z Daemon is ready

2024-11-09T11:58:27.532890140Z S3-Compatible-API server started, endpoint-url: http://0.0.0.0:6001

2024-11-09T11:58:27.532903829Z Experimental.Analytics is overridden by Experimental.StorageHostEnabled

2024-11-09T11:58:27.535121789Z Current host stats will be synced

2024-11-09T11:58:27.535135128Z Current host settings will be synced

2024-11-09T21:19:33.440342528Z LastSendCheques  map[] <nil>

2024-11-09T21:19:33.441370666Z LastSendCheques  map[] <nil>

2024-11-09T21:19:33.441388545Z LastSendCheques  map[] <nil>

2024-11-09T21:19:33.441393364Z LastSendCheques  map[] <nil>

2024-11-09T23:48:27.536480495Z every day, SendOnlineDaily, time:2024-11-09 23:48:27.536368888 +0000 UTC m=+42622.429683283

2024-11-09T23:48:33.983221169Z daily report online, resp = <nil>, err = rpc error: code = Unknown desc = nonce is too small, prev nonce 8336, new nonce 8321 

2024-11-09T23:49:17.483618274Z daily report online, resp = <nil>, err = rpc error: code = Unknown desc = nonce is too small, prev nonce 8336, new nonce 8321 

2024-11-09T23:50:21.502237581Z daily report online, resp = <nil>, err = rpc error: code = Unknown desc = nonce is too small, prev nonce 8336, new nonce 8321 

2024-11-09T23:58:27.535673725Z every day, SendOnlineDaily, time:2024-11-09 23:58:27.535554924 +0000 UTC m=+43222.428868900

2024-11-09T23:58:34.105369575Z daily report online, resp = <nil>, err = rpc error: code = Unknown desc = nonce is too small, prev nonce 8336, new nonce 8321 

2024-11-10T00:00:10.075602478Z daily report online, resp = <nil>, err = rpc error: code = Unknown desc = nonce is too small, prev nonce 8336, new nonce 8321 

2024-11-10T00:00:54.084807578Z daily report online, resp = <nil>, err = rpc error: code = Unknown desc = nonce is too small, prev nonce 8336, new nonce 8321`
