### ISSUE TITLE
Feature request: Environmental variable for Api Endpoint URL

### ISSUE THREAD

**Issue by solipsist01** [bittorrent/btfs-dashboard#9]
Hello.

I reverse proxy my nodes web interfaces.
When i put in the right api url in the settings (like https://btfs.hostname.com), this setting gets saved in the cookie of btfs.hostname.com (i think?)

I don't know if the design as it stands allows for this, but i'd like to be able to force, or, prefill this address with an environmental variable when i spin up the docker container.

the docker-compose.yml would look something like:

```
    environment:
      - BTFS_API_ENDPOINT=https://btfs.hostname.com
```

Or, perhaps the webinterface could derive the api URL from the forwarded hostheaders ? I beleive the previous 1.6 webinterface didn't require manual configuration of this API Endpoint URL ?

**Comment by daniel-tron** [comment]
got your need, not sure 1.6 behaviour behind reverse proxy currently, will discuss with our devs.

**Comment by solipsist01** [comment]
around february, a change as made so that the api url would accept https://btfs.hostname.com
Now i get the error again that it's an invalid API url

i have other nodes which still have the api url in the cookie, which it has pre migration. that one still works.

can the javascript sanitization be adjusted, so it accepts **https**://whater.hostname.com ?

it's function urlCheck.js in https://github.com/bittorrent/btfs-dashboard/blob/master/src/utils/checks.js starting at line 21

Thank you.
